package com.example.mudanu.model;

import java.util.ArrayList;

public class DaiData {
    public static String [][] data = new String[][]{
            {"Gus Baha", "Santri kesayangan Hadratus Syaikh Maimoen Zubair. Alumni pesantren Al-Anwar, Sarang, Rembang.", "Gus Baha’ atau KH. Baha’uddin Nursalim adalah alumni pesantren Al-Anwar, Sarang, Rembang. Seorang santri kesayangan Hadratus Syaikh Maimoen Zubair. Tak kurang dari mufassir sekalibar Prof. Quraish Syihab, memuji kecerdasan Gus Baha. Menurut ayahanda Najwa Shihab itu, Gus Baha adalah sosok langka karena menguasai tafsir sekaligus fikih. Selesai mengahafal Alquran beserta qiroahnya kepada ayahanda Kiai Nursalim di Kragan, Rembang, Baha kemudian melanjutkan pengajiannya di pesantren Mbah Moen. Di bawah asuhan Mbah Moen, Gus Baha menghafal berbagai kitab klasik, mulai dari Fathul Mu’in (fiqih), Shahih Muslim lengkap beserta matan dan sanadnya (hadis), dan kitab-kitab lain. Sudah barang tentu kitab tata bahasa Arab seperti Imrithi dan Alfiyah, tandas dihafalnya. Sekalipun hanya mengaji di pesantren asuhan ayahnya dan Mbah Moen, kepakaran Gus Baha mulai meramaikan jagat intelektual Islam Indonesia. Ia masuk dalam jajaran Dewan Tafsir Nasional, Ketua Tim Lajnah Mushaf UII, Penasehat BAZNAS, dan lain-lain. Konon, ia pernah ditawari untuk menerima gelar doktor honoris causa dari UII, tapi ia menolaknya. Gus Baha adalah produk pesantren Indonesia, dengan kealiman yang pilih tanding. Penampilannya yang sederhana, justru menunjukkan kepercayaan dirinya yang kuat. Tak ad serban yang menjuntai ataupun jubah. Bahkan, cara memakai pecinya yang agak semerawut, seperti santri yang sedang leyeh-leyeh di serambi asrama. Kemewahannya adalah saat mengutip beragam riferensi kitab-kitab klasik. Bahasanya yang sederhana dan lugas, mudah dicerna oleh pendengar dan pemirsa.","https://www.bengkulutoday.com/sites/default/files/article/2019-06/gus%20baha.jpg"},
            {"Gus Nadir", "Ketua PCINU Australia-Selandia Baru sejak 2005. Dosen tetap di Monash University Faculty of Law.", "Dr. H. Nadirsyah Hosen, LL.M., M.A. (Hons), Ph.D. adalah orang Indonesia yang menjadi dosen tetap di fakultas hukum di universitas di Australia. Sejak pertengahan tahun 2015 dia mengajar di Monash University Faculty of Law[1] setelah sebelumnya selama 8 tahun ia mengajar pada Fakultas Hukum, Universitas Wollongong (2007-2015), hingga meraih posisi sebagai Associate Professor. Tahun 2005 ia bekerja sebagai post-doctoral research fellow di TC. Beirne School of Law. Dr. Hosen lulus sarjana S1 dari Fakultas Syari'ah, IAIN Syarif Hidayatullah Jakarta dan meraih gelar Graduate Diploma in Islamic Studies serta Master of Arts with Honours dari Universitas New England. Kemudian ia meraih gelar Master of Laws dari Universitas Northern Territory.Peraih dua gelar doktor (PhD in Law dari Universitas Wollongong dan PhD in Islamic law dari National University of Singapore) ini telah melahirkan lebih dari 20 artikel di jurnal internasional. ","https://upload.wikimedia.org/wikipedia/id/thumb/0/01/Nadirsyah_Hosen.jpeg/220px-Nadirsyah_Hosen.jpeg"},
            {"Gus Ulil", "Berasal dari keluarga Nahdlatul Ulama. Penerus pesantren Mansajul Ulum, Pati. Menantu dari KH. Mustofa Bisri.", "Ulil Abshar Abdalla lebih kesohor sebagai seorang dedengkot Jaringan Islam Liberal. Kini, dia kembali menyuntuki khazanah kerohanian. Sejak 2016, mantan Direktur Freedom Institute itu mengampu pengajian secara daring. Kitab dibahas pun tak main-main. Sebuah magnus opus dari cendekiawan muslim Persia, Abu Hamid Muhammad bin Muhammad Al Ghazali, berjudul Ihya Ulumiddin. seorang tokoh Islam Liberal di Indonesia yang berafiliasi dengan Jaringan Islam Liberal. Ulil berasal dari keluarga Nahdlatul Ulama. Ayahnya Abdullah Rifa'i dari pesantren Mansajul Ulum, Pati, sedang mertuanya, Mustofa Bisri, kyai dari pesantren Raudlatut Talibin, Rembang.","https://pbs.twimg.com/profile_images/982775097604763649/Js706uM4_400x400.jpg"},
            {"Gus Muwafiq", "Orator NU masa kini. Kiai asal Jombor, Jogja.", "Gus Muwafiq dikenal sebagai salah satu orator NU zaman sekarang karena kedalaman ilmu dan kemampuan orasi yang dimiliki. Selain ulama' yang faham ilmu agama, Gus Muwafiq juga mendalami berbagai ilmu lain, salah satunya ilmu sejarah dan peradaban yang disampaikan dengan bahasa yang lugas dan mudah diterima. Gus Muwafiq pernah menjabat sebagai asisten pribadi KH. Abdurrahman Wahid (Gus Dur), termasuk saat menjabat sebagai Presiden Republik Indonesia. Gus Muwafiq juga dikenal sebagai Kyai dengan pemahaman sejarah yang sangat mendalam, mulai sejarah peradaban manusia secara umum, sejarah Agama Islam pada masa kenabian, hingga sejarah Nusantara. Begitu pun sejarah agama Islam di Indonesia, mulai awal perkembangan hingga saat ini. Gus Muwafiq dapat menjelaskan dengan jelas dan mudah difahami tentang setiap maksud dan makna filosofis dari setiap ajaran dan anjuran para kyai tentang khas dakwah di Nusantara.","https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gus_Muwafiq_Official.jpg/250px-Gus_Muwafiq_Official.jpg"},
            {"Gus Miftah","Pimpinan pesantren Ora Aji di Sleman. Salah satu ulama muda yang fokus dakwah bagi kaum marjinal.", "Miftah Maulana Habiburrahman atau lebih dikenal dengan Gus Miftah (lahir di Lampung, 05 Agustus 1981; umur 38 tahun) adalah seorang ulama, da'i, dan pimpinan Pondok Pesantren Ora Aji di Sleman, Yogyakarta. Gus Miftah juga dikenal sebagai ulama muda Nahdlatul 'Ulama yang fokus berdakwah bagi kaum marjinal, baik melalui dakwah di dalam maupun di luar pesantren. Perjalanan dakwah Gus Miftah, kyai asal Ponorogo kelahiran Lampung ini dimulai saat usianya masih 21 tahun. Pada sekitar tahun 2000-an, Gus Miftah yang sering salat tahajud di sebuah musala sekitar Sarkem, sebuah area lokalisasi di Yogyakarta, kemudian berniatan berdakwah. Saat itu ia ditemani Gunardi atau Gun Jack sosok yang menjadi penguasa pada saat itu. Bermula dari kegiatan tersebut, kajian agama mulai rutin digelar oleh Gus Miftah. Meski awalnya banyak tantangan, tapi saat ini sejumlah pekerja dunia malam sudah menerima kehadirannya. Tidak jarang, ketika pengajian sejumlah jemaah meneteskan air mata dan mulai merubah perilakunya secara perlahan.","https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Miftah_Maulana_Habiburrahman.jpg/220px-Miftah_Maulana_Habiburrahman.jpg"},
            {"Ayang Utriza", "Intelektual muda NU. Wakil Ketua Lembaga Takmir Masjid PBNU.", "MA Hukum Islam (Visiting Student) di Fakultas Syariah Universitas Al-Azhar Kairo (2001-2002)/Visiting Research Fellow di Oxford Centre for Islamic Studies (OXCIS), University of Oxford, Inggris (2012)/Visiting Fellow di Islamic Legal Studies Program (ILSP), Harvard Law School, Harvard University, Amerika Serikat (2013)/Postdoctoral Fellow di University of Louvain, Belgium (2016-2020)/Wakil Ketua LTM-PBNU (2015-2020)/Direktur Indonesian Sharia Watch","https://pbs.twimg.com/profile_images/1104305847063273472/ZwD4Yuzi_400x400.png"},
            {"Gus Ghofur Maimoen", "Katib Syuriah PBNU. Putra kelima KH. Maimoen Zubari. Menyelesaikan disertasi setebal 1700 halaman di Al-Azhar, Mesir.", "beliau menyelesaikan pendidikan di MGS tahun 1992. kemudian tahun 1993 beliau melanjutkan studinya di Al-Azhar University, Kairo. Hal tersebut merupakan suatu yang baru dalam tradisi pendidikan putra-putri Mbah Moen. Belum ada sebelumnya purta-putri Mbah Moen yang melanjutkan studi di dunia perkuliahan. Progam S1 Fakultas Usuhuludin jurusan Tafsir di Al-Azhar beliau selesaikan selama empat tahun. semua hasil ujian beliau selalu mendapatkan nilai Jayiid Jiddan, sebuah prestai langka di kalangan mahasiswa Indonesia di Kairo. Hal tersebut beliau pertahankan dalam ketika menjalani Program S2 di jurusan yang sama, selama dua tahun beliau selalu mendapat hasil akhir Jayyid Jiddan.","https://staialanwar.ac.id/wp-content/uploads/2017/01/abah-ghofur.jpg"},
            {"Habib Isamil Fajrie Alatas", "Asisten profesor Kajian Islam dan Timur Tengah di New York University", "Menarik jika mengupas tentang fenomena habib yang kini kian menjamur di Indonesia. Ada beberapa fenomena yang belakangan tersorot media, seperti kerusuhan yang sering dilakukan oleh salah satu organisasi Islam dan sering kali merugikan banyak orang lantaran sikapnya yang radikal serta yang terakhir booming adalah berita mengenai seorang yang mengaku habib namun ia dituding melakukan pelecehan seksual terhadap santrinya. Berbeda dengan fenomena tersebut, Ismail Fajrie Alatas, seorang humanis yang juga seorang habib dan lebih dikenal dengan pemikiran intelektualnya yang menggabungkan sisi antropolgi dengan agama.","https://panrita.id/wp-content/uploads/2018/10/Ismail-Fajrie-Alatas_NYU_panritainstitute.com_.jpg"},
            {"Habib Jindan", "Habib Jindan bin Novel bin Salim Jindan, dilahirkan di Sukabumi tanggal 21 Desember 1977 atau bertepatan dengan 10 Muharram 1398 Hijriah, adalah da'i, ulama, dan pimpinan Yayasan Al Fachriyah, Tangerang, Banten. Pimpinan Yayasan Al Fachriyah, Tangerang, Banten. Cucu dari Habib Salim bin Ahmad bin Jindan.", "Habib Jindan memimpin Yayasan Al Fachriyah Al Habib Novel bin Salim bin Jindan, menjadi anggota inti Majelis Syura yang dibentuk dan ditunjuk oleh Habib Umar bin Hafizh, menjadi penasehat Majelis Silaturahmi ulama dan habaib kota Tangerang, dan menjadi anggota senior Majelis Alwafa Bi Ahdillah. Majelis rutin yang diadakan ayah lima anak ini antara lain: pengajian dua minggu sekali, Rabu sore di Majelis Taklim Darul Musthofa Al Habib Muhammad Al Atthas di Condet. Pengajian malam jumat di Yayasan Al Fachriyah Ciledug.","https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Habib_Jindan.jpg/220px-Habib_Jindan.jpg"},
            {"Gus Candra", "Budayawan yang juga pengasuh pesantren Asy-Syahadah Karanganyar, Jawa Tengah. Tokoh Sufi.", "Candra Malik (lahir di Surakarta, Jawa Tengah, 25 Maret 1978; umur 41 tahun) adalah pengasuh Pondok Pesantren Asy-Syahadah di Kabupaten Karanganyar, Jawa Tengah. Namanya juga dikenal sebagai tokoh sufi, sastrawan, wartawan, penyanyi lagu reliji, pemeran film, penulis sejumlah kolom di berbagai media massa, dan pencipta lagu reliji yang kemudian disebut sebagai kidung sufi. Sejumlah karya sastra Candra Malik pernah dipublikasikan di berbagai media massa antara lain Kompas, Majalah Sastra Horison, Koran Tempo Minggu, Suara Merdeka, Suara Karya, dan Majalah Femina. Lagunya, Syahadat Cinta menjadi original sound track (OST) Cinta Tapi Beda, film yang disutradarai oleh Hanung Bramantyo (2013).[1][2] Sejak 2015, Candra Malik menjabat sebagai Wakil Ketua Pengurus Pusat Lembaga Seni Budaya Muslim Indonesia (PP Lesbumi) PBNU untuk periode 2015-2020.","https://pbs.twimg.com/profile_images/931724061226311680/NSFKZ0AH_400x400.jpg"},
    };

    public static ArrayList<Dai> getListData(){
        ArrayList<Dai> list = new ArrayList<>();
        for (String[] aData : data){
            Dai dai = new Dai();
            dai.setName(aData[0]);
            dai.setInfo(aData[1]);
            dai.setDesc(aData[2]);
            dai.setPhoto(aData[3]);

            list.add(dai);
        }

        return list;
    }
}
